version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-patch"

  - package-ecosystem: bundler
    directory: "/examples/rails_example"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"

  - package-ecosystem: bundler
    directory: "/examples/sinatra"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "*"
