# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in featurehub-sdk.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"

gem "rubocop", "~> 1.21"

gem "simplecov", "~> 0.21"

gem "concurrent-ruby", "~> 1.1.10"

gem "faraday", '~> 2.3'
