# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in featurehub-sdk.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 8.0"

gem "rubocop", "~> 1.21"

gem "simplecov", "~> 0.21"

gem "concurrent-ruby", "~> 1.3"

gem "faraday", "~> 2"

gem "murmurhash3", "~> 0.1.7"

gem "sem_version", "~> 2.0.0"

gem "ld-eventsource", "~> 2.3.0"
