services:
  party-server:
    image: featurehub/party-server:latest
    ports:
      - 8085:8085
    user: 999:999
    # allow us to restart the server causing the client to lose connectivity
    # but when we start it again its OK
    volumes:
      - featurehub-h2-data:/db
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  memcache:
    image: memcached:1.6-alpine
    ports:
      - 11211:11211
  sinatra:
    image: todo-server:e2e
    ports:
      - 8099:8099
    environment:
      RAILS_ENV: production
      FEATUREHUB_CLIENT_API_KEY: "a1286d73-a23b-4f5b-8fdf-04dd03668fb9/xPlhDYnWlKjjZ3maUPquhOUOmk50gn*Hh8Q5qY6JEURrxtEEjzk"
      FEATUREHUB_EDGE_URL: http://party-server:8085
      FEATUREHUB_BASE_URL: http://party-server:8085
  sinatra-redis:
    image: todo-server:e2e
    ports:
      - 8099:8099
    environment:
      FEATUREHUB_POLLING_INTERVAL: "3"
      FEATUREHUB_CLIENT_API_KEY: "a1286d73-a23b-4f5b-8fdf-04dd03668fb9/xPlhDYnWlKjjZ3maUPquhOUOmk50gn*Hh8Q5qY6JEURrxtEEjzk"
      FEATUREHUB_EDGE_URL: http://party-server:8085
      FEATUREHUB_BASE_URL: http://party-server:8085
      FEATUREHUB_REDIS_STORE: redis://redis:6379
  sinatra-memcache:
    image: todo-server:e2e
    ports:
      - 8099:8099
    environment:
      RAILS_ENV: production
      FEATUREHUB_POLLING_INTERVAL: "3"
      FEATUREHUB_CLIENT_API_KEY: "a1286d73-a23b-4f5b-8fdf-04dd03668fb9/xPlhDYnWlKjjZ3maUPquhOUOmk50gn*Hh8Q5qY6JEURrxtEEjzk"
      FEATUREHUB_EDGE_URL: http://party-server:8085
      FEATUREHUB_BASE_URL: http://party-server:8085
      FEATUREHUB_MEMCACHE_STORE: memcache
    depends_on:
      - memcache
volumes:
  featurehub-h2-data:
