# frozen_string_literal: true

source "https://rubygems.org"

ruby "2.7.6"

gem "rack"
gem "sinatra"
# gem "featurehub-sdk", path: "../../"
gem "featurehub-sdk", git: "https://github.com/featurehub-io/featurehub-ruby-sdk.git",
                      glob: "featurehub-sdk/*.gemspec"

group :development do
  gem "shotgun"
  gem "thin"
end
