# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.10"

# 5 prevents us using ruby 3.2 which while EOL is still in our build
gem "dalli", "~> 4"
gem "featurehub-sdk", path: "../.."
# this is just to test 1.x works OK
gem "faraday", "~> 1"
gem "rack"
gem "redis"
gem "sinatra"
# gem "featurehub-sdk", git: "https://github.com/featurehub-io/featurehub-ruby-sdk.git",
#                       glob: "featurehub-sdk/*.gemspec"

group :development do
  gem "shotgun"
  gem "thin"
end
