= Sinatra Example

This is a simple todo server example that we use to run our Cucumber tests against
to ensure that the SDK is operating as expected. Please read the `application.rb`
for details on how it works, it is fairly simple.

NOTE: The `Dockerfile` is intended for use in the e2e tests in the pipeline and is not a general use-case sample. It uses Passenger, Sinatra and the FeatureHub SDK on this specific branch. It is, as such, constructed from the root directory (using the `Makefile`).

We typically want to run one cache and then two copies of the server. We would normally disconnect the primary server (running on 8099) from edge, leaving the second server running (8100) and writing to the cache.

To disconnect from edge, call `curl localhost:8099/health/disconnect`

The tests should still pass as the primary server is picking up changes from the cache.

== Redis

----
docker run -d -p 6379:6379 --name redis redis

----

== Memcache

----
docker run -p 11211:11211 --name memcache -d memcached
----
