server {
    listen 80;
    server_name localhost;
    root /app/featurehub/examples/sinatra;

    passenger_enabled on;
    passenger_user root;

    # If this is a Ruby app, specify a Ruby version:
    # For Ruby 3.3
    passenger_ruby /usr/bin/ruby3.3;

    # Nginx has a default limit of 1 MB for request bodies, which also applies
    # to file uploads. The following line enables uploads of up to 50 MB:
    #client_max_body_size 50M;
}